// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerticalSliceDance.Infrastructure;

#nullable disable

namespace VerticalSliceDance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VerticalSliceDance.Domain.DanceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("DanceClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Title = "Salsa Beginners"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Title = "Salsa Advanced"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Hip Hop Intermediate"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Title = "Bachata Beginners"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222224"),
                            Title = "Kizomba Beginners"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444446"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Title = "Breakdance Kids"
                        });
                });

            modelBuilder.Entity("VerticalSliceDance.Domain.DanceStudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DanceStudios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Bulevar Oslobođenja 12",
                            Name = "Rhythm Studio"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Address = "Narodnog Fronta 45",
                            Name = "Salsa Nation"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Address = "Zmaj Jovina 8",
                            Name = "Urban Dance Hub"
                        });
                });

            modelBuilder.Entity("VerticalSliceDance.Domain.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            FirstName = "Ana",
                            LastName = "Jovanović",
                            StudioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            FirstName = "Marko",
                            LastName = "Petrović",
                            StudioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            FirstName = "Jovana",
                            LastName = "Nikolić",
                            StudioId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            FirstName = "Stefan",
                            LastName = "Ilić",
                            StudioId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            FirstName = "Milica",
                            LastName = "Radovanović",
                            StudioId = new Guid("11111111-1111-1111-1111-111111111113")
                        });
                });

            modelBuilder.Entity("VerticalSliceDance.Domain.DanceClass", b =>
                {
                    b.HasOne("VerticalSliceDance.Domain.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VerticalSliceDance.Domain.ClassSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("DanceClassId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time");

                            b1.HasKey("DanceClassId");

                            b1.ToTable("DanceClasses");

                            b1.WithOwner()
                                .HasForeignKey("DanceClassId");

                            b1.HasData(
                                new
                                {
                                    DanceClassId = new Guid("44444444-4444-4444-4444-444444444441"),
                                    Day = 1,
                                    EndTime = new TimeOnly(19, 30, 0),
                                    StartTime = new TimeOnly(18, 0, 0)
                                },
                                new
                                {
                                    DanceClassId = new Guid("44444444-4444-4444-4444-444444444442"),
                                    Day = 3,
                                    EndTime = new TimeOnly(21, 0, 0),
                                    StartTime = new TimeOnly(19, 30, 0)
                                },
                                new
                                {
                                    DanceClassId = new Guid("44444444-4444-4444-4444-444444444443"),
                                    Day = 2,
                                    EndTime = new TimeOnly(18, 30, 0),
                                    StartTime = new TimeOnly(17, 0, 0)
                                },
                                new
                                {
                                    DanceClassId = new Guid("44444444-4444-4444-4444-444444444444"),
                                    Day = 4,
                                    EndTime = new TimeOnly(21, 30, 0),
                                    StartTime = new TimeOnly(20, 0, 0)
                                },
                                new
                                {
                                    DanceClassId = new Guid("44444444-4444-4444-4444-444444444445"),
                                    Day = 5,
                                    EndTime = new TimeOnly(20, 0, 0),
                                    StartTime = new TimeOnly(18, 30, 0)
                                },
                                new
                                {
                                    DanceClassId = new Guid("44444444-4444-4444-4444-444444444446"),
                                    Day = 6,
                                    EndTime = new TimeOnly(11, 30, 0),
                                    StartTime = new TimeOnly(10, 0, 0)
                                });
                        });

                    b.Navigation("Instructor");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("VerticalSliceDance.Domain.Instructor", b =>
                {
                    b.HasOne("VerticalSliceDance.Domain.DanceStudio", "DanceStudio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanceStudio");
                });
#pragma warning restore 612, 618
        }
    }
}
